import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "HOME": "الصفحة الرئيسية",
          "Purchases": "الشراء",
          "Make Sale": "البيع",
          "Suppliers": "الموردين",
          "Inventory": "المخزون",
          "Accounts": "الحسابات",
          "Performance": "الاداء",
          "Generate Offers": "التخفيضات المقترحة",
          "Reset Maneger Password": "تغير كلمة مرور المدير",
          "Reset Password": "تغير كلمة المرور",
          "Logout": "تسجيل الخروج",
          "Are You Sure?": "هل انت متأكد؟",
          "Cancel": "القاء",
          "Yes": "نعم",
          "Product Name": "اسم المنتج",
          "Cost": "سعر الشراء",
          "Price": "سعر البيع",
          "Quantity": "الكمية",
          "Available Quantity": "الكمية المتوفرة",
          "Total": "المجموع",
          "TOTAL": "المجموع",
          "Sold Quantity": "الكمية المباعة",
          "Search Product Name Or SN": "ابحث باسم المنتج او رقمه التسلسلي",
          "Choose Bill Date": "اختر تاريخ الفاتورة",
          "Make A Sale": "عمليات البيع",
          "Buy from a Supplier": "الشراء من مورد",
          "Payment": "الدفع",
          "BUY": "شراء",
          "Cashier Screens": "شاشات البيع",
          "Cashier 1": "الشاشة 1",
          "Cashier 2": "الشاشة 2",
          "Show List Of Suppliers": "إظهار قائمة الموردين",
          "Add New Supplier": "إضافة مورد جديد",
          "Supplier Phone Number": "رقم هاتف المورد",
          "Supplier Name": "اسم المورد",
          "Save": "حفظ",
          "Phone number": "رقم الهاتف",
          "Suppliers List": "قائمة الموردين",
          "Search By Supplier Name": "البحث باسم المورد",
          "Show List Of Products": "اظهار قائمة المنتجات",
          "Add New Product": "اضافة منتج جديد",
          "Product Serial Number": "الرقم التسلسلي للمنتج",
          "Category": "الفئة",
          "Expiration Date": "تاريخ الصلاحية",
          "Products List": "قائمةالمنتجات",
          "Delete": "حذف",
          "Edit": "تعديل",
          "Search By Product Name": "البحث باسم المنتج",
          "Login": "تسجيل الدخول",
          "Sign Up": "انشاء حساب",
          "Name": "الاسم",
          "Password": "كلمة المرور",
          "Email": "البريد الالكتروني",
          "Don't Have An Account?": "ليس لديك حساب؟",
          "The e-mail not valid": "البريد الالكتروني غير صالح",
          "The field is empty": "الحقل فارغ",
          "Already Have A Account?": "لديك حساب بالفعل؟",
          "Maneger Password": "كلمة مرور المدير",
          "Maneger": "مدير",
          "Employees": "موظف",
          "Changing": "تغير",
          "The password is less than 8 char": "كلمة المرور اقل من 8 احرف",
          "Your phone number is less than 10": "عدد ارقام الهاتف اقل من 10",
          "Supplier Invoices": "فواتير المورد",
          "From": "من",
          "To": "الى",
          "Dashboard": "لوحة الاداء",
          "Seles Reports": "تقارير المبيعات",
          "Store Movement": "حركة المتجر",
          "Best Selling Chart": "رسم بياني يوضح لاكثر المنتجات مبيعا",
          "Least Selling Chart": "رسم بياني يوضح اقل المنتجات مبيعا",
          "Low Stock Products": "رسم بياني يوضح المنتجات منخفضة المخزون",
          "Sales": "المبيعات",
          "Balance": "الرصيد",
          "Revenue": "الايرادات",
          "New Password": "كلمة المرور الجديدة",
          "Current Password": "كلمة المرور الحالية",
          "Product Information": "معلومات المنتج",
          "New Quantity": "الكمية الجديدة",
          "Old cost": "سعر الشراء القديم",
          "New cost": "سعر الشراء الجديد",
          "Delete Product From List": "حذف المنتج من القائمة",
          "Payment Bill": "فاتورة الدفع",
          "Payed": "المدفوع",
          "Change": "الباقي",
          "Save This Bill To A Supplier Account": "حفظ الفاتورة في حساب المورد",
          "Search Result": "نتيجة البحث",
          "The product has deleted": "تم حذف المنتج",
          "Done": "تم",
          "Success process": "تمت العملية بنجاح",
          "Offer Strategy": "طريقة التخفيض",
        },
        "en": {
          "HOME": "HOME",
          "Purchases": "Purchases",
          "Make Sale": "Make Sale",
          "Suppliers": "Suppliers",
          "Inventory": "Inventory",
          "Accounts": "Accounts",
          "Performance": "Performance",
          "Generate Offers": "Generate Offers",
          "Reset Maneger Password": "Reset Maneger Password",
          "Reset Password": "Reset Password",
          "Logout": "Logout",
          "Cancel": "Cancel",
          "Yes": "Yes",
          "Product Name": "Product Name",
          "Cost": "Cost",
          "Price": "Price",
          "Quantity": "Quantity",
          "Available Quantity": "Available Quantity",
          "Total": "Total",
          "TOTAL": "TOTAL",
          "Sold Quantity": "Sold Quantity",
          "Search Product Name Or SN": "Search Product Name Or SN",
          "Choose Bill Date": "Choose Bill Date",
          "Make A Sale": "Make A Sale",
          "Buy from a Supplier": "Buy from a Supplier",
          "Payment": "Payment",
          "BUY": "BUY",
          "Cashier Screens": "Cashier Screens",
          "Cashier 1": "Cashier 1",
          "Cashier 2": "Cashier 2",
          "Show List Of Suppliers": "Show List Of Suppliers",
          "Add New Supplier": "Add New Supplier",
          "Supplier Phone Number": "Supplier Phone Number",
          "Supplier Name": "Supplier Name",
          "Save": "Save",
          "Phone number": "Phone number",
          "Suppliers List": "Suppliers List",
          "Search By Supplier Name": "Search By Supplier Name",
          "Show List Of Products": "Show List Of Products",
          "Add New Product": "Add New Product",
          "Product Serial Number": "Product Serial Number",
          "Category": "Category",
          "Expiration Date": "Expiration Date",
          "Products List": "Products List",
          "Delete": "Delete",
          "Edit": "Edit",
          "Search By Product Name": "Search By Product Name",
          "Login": "Login",
          "Name": "Name",
          "Email": "Email",
          "Sign Up": "Sign Up",
          "Password": "Password",
          "The e-mail not valid": "The e-mail not valid",
          "The field is empty": "The field is empty",
          "Don't Have An Account?": "Don't Have An Account?",
          "Already Have A Account?": "Already Have A Account?",
          "Maneger Password": "Maneger Password",
          "Maneger": "Maneger",
          "Employees": "Employees",
          "Changing": "Changing",
          "The password is less than 8 char":
              "The password is less than 8 char",
          "Supplier Invoices": "Supplier Invoices",
          "From": "From",
          "To": "To",
          "Store Movement": "Store Movement",
          "Best Selling Chart": "Best Selling Chart",
          "Least Selling Chart": "Least Selling Chart",
          "Low Stock Products": "Low Stock Products",
          "Sales": "Sales",
          "Balance": "Balance",
          "Revenue": "Revenue",
          "New Password": "New Password",
          "Current Password": "Current Password",
          "Product Information": "Product Information",
          "New Quantity": "New Quantity",
          "Old cost": "Old cost",
          "New cost": "New cost",
          "Delete Product From List": "Delete Product From List",
          "Payment Bill": "Payment Bill",
          "Payed": "Payed",
          "Change": "Change",
          "Save This Bill To A Supplier Account":
              "Save This Bill To A Supplier Account",
          "Search Result": "Search Result",
          "The product has deleted": "The product has deleted",
          "Done": "Done",
          "Success process": "Success process",
          "Offer Strategy": "Offer Strategy",
        },
      };
}
